version: '3.7'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 5000:5000
  osrm:
    build:
      context: .
      dockerfile: Dockerfile.osrm
    restart: always
    ports:
      - 5050:5050
