version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5050:5050
    links:
      - "osrm:osrm"
    environment:
      - OSRM=http://osrm:5000
    volumes:
      # - ./instance/gs.db:/app/instance/gs.db
      - .:/app
    depends_on:
      - osrm
  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./osrm:/data
    command: "osrm-routed --algorithm mld --max-table-size 5000000 /data/southern-zone-latest.osrm"
  frontend:
    build:
      context: ./gs-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend